package com.example.erp_service_sales.service;
import com.example.erp_service_sales.config.TenantContext;
import com.example.erp_service_sales.entity.*; import com.example.erp_service_sales.repository.*;
import org.springframework.kafka.core.KafkaTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.example.erp_service_sales.kafka.FinanceIntegrationProducer;
import java.math.*; import java.time.*; import java.util.*;
@Service public class SalesService {
 private final CustomerRepository customers; private final QuotationRepository quotations; private final QuotationLineRepository quoteLines; private final SalesOrderRepository orders; private final SalesOrderLineRepository orderLines; private final InvoiceRepository invoices; private final PaymentRepository payments; private final ReturnRequestRepository returns; private final CreditNoteRepository credits; private final KafkaTemplate<String,Object> kafka; private final FinanceIntegrationProducer finance;
 public SalesService(CustomerRepository c,QuotationRepository q,QuotationLineRepository ql,SalesOrderRepository o,SalesOrderLineRepository ol,InvoiceRepository i,PaymentRepository p,ReturnRequestRepository r,CreditNoteRepository cn,KafkaTemplate<String,Object> k,FinanceIntegrationProducer f){customers=c;quotations=q;quoteLines=ql;orders=o;orderLines=ol;invoices=i;payments=p;returns=r;credits=cn;kafka=k;finance=f;}
 private String tenant(){return TenantContext.required();} private <T> T own(Optional<T> value){return value.orElseThrow(()->new NoSuchElementException("Resource not found"));}
 public List<Customer> customers(){return customers.findByTenantId(tenant());} public Customer customer(Customer c){c.setId(null);c.setTenantId(tenant());return customers.save(c);} public Customer customer(Long id,Customer c){Customer x=own(customers.findByIdAndTenantId(id,tenant())); c.setId(x.getId());c.setTenantId(x.getTenantId());return customers.save(c);}
 @Transactional public Quotation quotation(Quotation q,List<QuotationLine> lines){String t=tenant();q.setId(null);q.setTenantId(t);q.setTotal(BigDecimal.ZERO);Quotation saved=quotations.save(q);BigDecimal total=BigDecimal.ZERO;for(QuotationLine l:lines){l.setId(null);l.setTenantId(t);l.setQuotationId(saved.getId());l.setLineTotal(l.getQuantity().multiply(l.getUnitPrice()));total=total.add(l.getLineTotal());quoteLines.save(l);}saved.setTotal(total);return quotations.save(saved);}
 public List<Quotation> quotations(){return quotations.findByTenantId(tenant());}
 @Transactional public SalesOrder order(SalesOrder o,List<SalesOrderLine> lines){String t=tenant();Customer c=own(customers.findByIdAndTenantId(o.getCustomerId(),t));o.setId(null);o.setTenantId(t);o.setStatus("PENDING_CREDIT_CHECK");o.setCreatedAt(Instant.now());o.setTotal(BigDecimal.ZERO);SalesOrder saved=orders.save(o);BigDecimal total=BigDecimal.ZERO;for(SalesOrderLine l:lines){l.setId(null);l.setTenantId(t);l.setOrderId(saved.getId());l.setLineTotal(l.getQuantity().multiply(l.getUnitPrice()));total=total.add(l.getLineTotal());orderLines.save(l);}saved.setTotal(total);if(c.getCreditLimit()!=null && c.getCreditLimit().compareTo(total)<0){saved.setStatus("CREDIT_HOLD");}else{saved.setStatus("CONFIRMED");saved.setReservedAmount(total);kafka.send("inventory-reservation-events",new ReservationEvent(t,saved.getId(),lines));}return orders.save(saved);}
 public List<SalesOrder> orders(){return orders.findByTenantId(tenant());} public SalesOrder order(Long id){return own(orders.findByIdAndTenantId(id,tenant()));}
 @Transactional public SalesOrder fulfillmentStatus(Long id,String status){SalesOrder o=order(id);if(!Set.of("CONFIRMED","FULFILLING","SHIPPED","DELIVERED","CANCELLED").contains(status))throw new IllegalArgumentException("Invalid fulfillment status");o.setStatus(status);return orders.save(o);}
 public boolean creditCheck(Long id){SalesOrder o=order(id);Customer c=own(customers.findByIdAndTenantId(o.getCustomerId(),tenant()));return c.getCreditLimit()==null||c.getCreditLimit().compareTo(o.getTotal())>=0;}
 @Transactional public Invoice invoice(Invoice i){String t=tenant();own(orders.findByIdAndTenantId(i.getOrderId(),t));i.setId(null);i.setTenantId(t);i.setPaidAmount(BigDecimal.ZERO);i.setStatus("OPEN");Invoice saved=invoices.save(i);finance.invoice(saved);return saved;} public List<Invoice> invoices(){return invoices.findByTenantId(tenant());}
 @Transactional public Payment payment(Payment p){String t=tenant();Invoice i=own(invoices.findByIdAndTenantId(p.getInvoiceId(),t));p.setId(null);p.setTenantId(t);p.setPaidAt(Instant.now());Payment saved=payments.save(p);i.setPaidAmount(i.getPaidAmount().add(p.getAmount()));if(i.getPaidAmount().compareTo(i.getTotal())>=0)i.setStatus("PAID");invoices.save(i);finance.payment(saved);return saved;}
 @Transactional public CreditNote returnAndCredit(ReturnRequest r){String t=tenant();own(orders.findByIdAndTenantId(r.getOrderId(),t));r.setId(null);r.setTenantId(t);r.setStatus("APPROVED");ReturnRequest saved=returns.save(r);CreditNote n=new CreditNote();n.setTenantId(t);n.setReturnId(saved.getId());n.setCreditNoteNumber("CN-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());n.setAmount(r.getAmount());return credits.save(n);}
 public record ReservationEvent(String tenantId,Long orderId,List<SalesOrderLine> lines){}
}
