input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [type] == "java-springboot" {
    mutate {
      add_field => { "[@metadata][index_name]" => "erp-logs-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "erp-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
